### PR TITLE
introduce bip buffer spsc atomic

### PR DESCRIPTION
**Pull request by bku-sue**
This is a clean and feature complete commit of the previously submitted version (#330), which in turn can be ignored.

### CODE REVIEW

**Comment by jwellbelove** [comment]
I noticed that clearing or destructing the buffer does not call the destructors for the buffered items. Was this bip buffer only intended for trivially destructible types?

Also, the top level template class does not define copy/move constructors or assignment operators. Should these be marked as disabled?

**Comment by bku-sue** [comment]
Yes, it's intended for raw data, but I guess destructing can be added as well if necessary.

I also don't see the use-case for copying the container, so it can be disabled.

**Comment by bku-sue** [comment]
Hi! Can I be of further assistance? Shall I fix the mentioned points and submit a follow-up PR?

**Comment by jwellbelove** [comment]
Yes, that would be helpful as I'm a bit bogged down with trying to get my new C++11/C++17 version of `etl::variant` working at the moment.

**Pull request merged**
