### PR TITLE
add static assert with auto message

### PR DESCRIPTION
**Pull request by dhebbeker**
Suggested changes:

- Add overload to function-like macro `ETL_STATIC_ASSERT()` for only one argument (condition). That overload does either call `static_assert()` if C++17 is used or calls `ETL_STATIC_ASSERT()` where the second (message) argument is generated by stringifying the condition.
- In order to perform overload resolution with function-like macros a helper macro has been added to resolve overloads of 1 or 2 arguments.

⚠ Warning: The overload resolution mechanism does use variadic macros (`__VA_ARGS__`). These were officially added in C99 and C++11. When compiling with `-std=c++98` modern compilers issue a warning (see [example](https://godbolt.org/#g:!((g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:'%23define+GET_MACRO_OVERLOAD2(_1,+_2,+SELECTED_MACRO_NAME,+...)+SELECTED_MACRO_NAME%0A%0A//+---%0A%0A%23define+TAKES1(+a+)+(a)%0A%23define+TAKES2(a,+b)+(a%2Bb)%0A%0A%23define+MULTI(...)+GET_MACRO_OVERLOAD2(__VA_ARGS__,+TAKES2,+TAKES1,+%22%22)(__VA_ARGS__)%0A%0A//+---%0A%0A%23include+%3Ciostream%3E%0A%23include+%3Cstdlib.h%3E%0A%0Aint+main()+%7B%0A++++using+namespace+std%3B%0A++++cout+%3C%3C+%22Result+1:+%22+%3C%3C+MULTI(+1+)+%3C%3C+endl%3B%0A++++cout+%3C%3C+%22Result+2:+%22+%3C%3C+MULTI(+1,+1+)+%3C%3C+endl%3B%0A++++return+EXIT_SUCCESS%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:44.49339207048458,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:pp,i:(clang-format:'1',editorid:1,filter-headers:'0',fontScale:14,fontUsePx:'0',j:1,treeid:0),l:'5',n:'0',o:'Preprocessor+Output+x86-64+gcc+(trunk)+(Editor+%231,+Compiler+%231)',t:'0')),header:(),k:38.86085212906417,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:gsnapshot,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B98+-x+c%2B%2B+-DETL_NO_PROFILE_HEADER+-DETL_NO_STL+-pedantic+-Wall+-Wextra',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+(trunk)+(Editor+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:55.50660792951542,l:'3',n:'0',o:'',t:'0')),l:'2',m:70.24704618689582,n:'0',o:'',t:'0'),(g:!((h:output,i:(compilerName:'x86-64+clang+(trunk)',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'0'),l:'5',n:'0',o:'Output+of+x86-64+gcc+(trunk)+(Compiler+%231)',t:'0')),header:(),l:'4',m:29.752953813104188,n:'0',o:'',s:0,t:'0')),l:'3',n:'0',o:'',t:'0')),version:4)). I also tested it with IAR C/C++ Compiler for AVR 6.70.1 which officially only supports C++98 (Extended Embedded C++), without warnings or errors.

In case these changes are accepted, the [documentation on the website](https://www.etlcpp.com/static_assert.html) must be updated.

### CODE REVIEW

**Comment by jwellbelove** [comment]
Any updates on this?

**Comment by dhebbeker** [comment]
Not yet. I have to rebase it to master, use `ETL_STRINGIFY` and cleanup. Also I wanted to have a look if I can add a (unit) test with reasonable effort. I haven't used ETL's internal test infrastructure yet.

Maybe I will find some time tomorrow.

**Comment by dhebbeker** [comment]
I rebased this branch in order to make use of the extended workflow settings (3173d7e784bf4276185a226cf1d62daee63a17f9).

**Comment by dhebbeker** [comment]
This branch is currently based on 4eb46d69d22b169ee3a589ed436cc14a33b491e7 of branch `dhebbeker:feature/try-to-fix-GitHub-Actions-for-clang-C++20` (#784). Those unrelated changes should not be part of this pull request. But they simplify to check the changes of this pull request as they fix unrelated failures in the workflow (GitHub Actions).

- [ ] unrelated changes must be removed from source branch

The unrelated changes will be removed from this pull request as soon as they will be merged into the target/base branch of this pull request. Alternatively the source branch of this pull request may be rebased onto its merge-base to the target/base branch while omitting the unrelated changes.

**Comment by jwellbelove** [comment]
I've just managed to get round to looking at this pull request and I noticed that it has a lot of 'co-authors', one at least involved with Linux. Has some of this change been copied from GPL code?

Co-authored-by: John Wellbelove <jwellbelove@users.noreply.github.com>
Co-authored-by: David Hebbeker <dhebbeker@users.noreply.github.com>
**Co-authored-by: Linus Torvalds <torvalds@ppc970.osdl.org>**
Co-authored-by: Zhaolei <zhaolei@cn.fujitsu.com>
Co-authored-by: John Wellbelove <john.wellbelove@etlcpp.com>
Co-authored-by: Soma Veszelovszki <soma.veszelovszki@gmail.com>
Co-authored-by: Andreas <and1p@web.de>
Co-authored-by: Andreas Pelczer <pelczer@stoerk-tronic.com>
Co-authored-by: H1MSK <ksda47832338@Outlook.com>
Co-authored-by: jmartens-42 <jmartens@jayhawk.us>
Co-authored-by: Josh <joshua.martens@magna.com>
Co-authored-by: John Wellbelove <john.wellbelove@etlcpp.co.uk>

**Comment by dhebbeker** [comment]
The branch contains some commits which were not supposed to be merged. A [rebase is required](https://github.com/ETLCPP/etl/pull/740#issuecomment-1803682100) to remove those, hence I did not mark the pull request as ready for merge.

I was not able to finish this pull request as I was not able to use the build pipeline to test the changes (see #784).

The only relevant changes for this pull request is the range including [7771cf31fd9691bcecfdf064c0945b75bd231e9a ... ba53a39cb8fd568942bab734543589b41b69e399] (see [comparison with parent](https://github.com/ETLCPP/etl/compare/4eb46d69d22b169ee3a589ed436cc14a33b491e7...ba53a39cb8fd568942bab734543589b41b69e399)). Those commits were authored my me.

**Pull request merged**
