### PR TITLE
fix(string_stream): add missing initializations of const format specifiers

### PR DESCRIPTION
**Pull request by KnoerleMaTLS**
This pull request introduces a possible fix for the issue #848 by adding the missing initializers.

### CODE REVIEW

**Comment by jwellbelove** [comment]
Were you getting warning from the compiler?

**Comment by KnoerleMaTLS** [comment]
Warning about what/where?
Regarding the propsed fix?

**Comment by jwellbelove** [comment]
Did you get errors or warnings about 'missing initializers'?
`left_spec` & `right_spec` have default constructors, so they shouldn't need explicit initialisation.

**Comment by KnoerleMaTLS** [comment]
Yeah, i got compiler errors about missing initializers for `left` and `right`.
Please check #848 for further details.

Yes, the structs `left_spec` and `right_spec` have compiler generated default constructors, but regarding the C++ standard this is not enough to initialize a const object (_"default-initialization of a const object could not call an implicitly declared default constructor"_).
I also tried to explain this in more detail in the mentioned issue.

**Pull request merged**
