### PR TITLE
Feature/introduce bip buffer spsc atomic

### PR DESCRIPTION
**Pull request by bku-sue**
This version is working quite reliably on our project now, any timeline for adding this to mainline?

### CODE REVIEW

**Comment by jwellbelove** [comment]
Do you have a set of ETL unit tests for this?

**Comment by bku-sue** [comment]
Unfortunately no.

**Comment by bku-sue** [comment]
Hello John,
What would it take to get this feature into the mainline?

**Comment by jwellbelove** [comment]
It needs to have a full set of unit tests. 
It especially needs to exercise all of the corner cases.

**Comment by bku-sue** [comment]
How can I easiest get started with building and running the unit tests?

**Comment by jwellbelove** [comment]
The easiest way could be to copy one of the thread safe queue unit tests. They also include an option 'real time' section at the end, using multiple threads.

**Comment by bku-sue** [comment]
I can build the tests, but runtests.sh returns with error: `./runtests.sh: 3: cd: can't cd to build`

**Comment by jwellbelove** [comment]
Try creating the directory 'build' under 'test'.

**Comment by bku-sue** [comment]
Allright, so the next roadblock (for all 4 build variants):
```
make: *** No targets specified and no makefile found.  Stop.
./runtests.sh: 13: ./runtests.sh: ./etl_tests: not found
```
The etl_tests is there: `-rwxr-xr-x  1 user user 44034072 Jun 14 15:04 etl_tests`

**Comment by jwellbelove** [comment]
./etl_tests should be the unit test executable. Can you try running it manually?
Maybe it doesn't have executable permissions?

**Comment by bku-sue** [comment]
Hi! I can run etl_tests directly, so that's working for the testing. I wanted to add `ETL_ASSERT_AND_RETURN()`s for invalid cases as it's described on https://www.etlcpp.com/error_handler.html, but the information on the website seems to be out of date, now only `ETL_ASSERT` and `ETL_ALWAYS_ASSERT` are present. I'd really prefer to use `ETL_ASSERT_AND_RETURN()` as it will just ignore false commits if the error handling is disabled. What's the preferred alternative then?

**Comment by jwellbelove** [comment]
ETL_ASSERT_AND_RETURN may not be in your branch. You will probably have to merge or rebase from development or master to get them.

**Pull request merged**
