### PR TITLE
fix c++20-compat false positive

### LINKED ISSUE #906: `platform.h` error when building with GCC 13 using C++14
Working or some minor improvements, and wanted to test them using C++14. Forced it in CMakeLists.txt. This started erroring out in `platform.h` because `char8_t` is a reserved identifier in C++20. The only way to get rid of the error (which seems a false positive given the codebase) was to add

```cmake
add_compile_options(-Wno-c++20-compat)
```

CMake patch to force C++14:

```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -32,6 +32,8 @@ add_library(etl::etl ALIAS ${PROJECT_NAME})
 
 include(GNUInstallDirs)
 
+add_compile_options(-std=c++14)
+
 target_include_directories(${PROJECT_NAME} ${INCLUDE_SPECIFIER} INTERFACE
         $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
         $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
```

Error:

```
[24/303] Building CXX object test/CMakeFiles/etl_tests.dir/murmurhash3.cpp.o
FAILED: test/CMakeFiles/etl_tests.dir/murmurhash3.cpp.o 
/usr/bin/c++ -DETL_DEBUG -I/home/jaskij/projects/deps/etl/test/../include -isystem /home/jaskij/projects/deps/etl/test/UnitTest++/.. -std=gnu++20 -std=c++14 -fno-omit-frame-pointer -fno-common -Wall -Wextra -Werror -Wfloat-equal -Wuseless-cast -Wshadow -Wnull-dereference -MD -MT test/CMakeFiles/etl_tests.dir/murmurhash3.cpp.o -MF test/CMakeFiles/etl_tests.dir/murmurhash3.cpp.o.d -o test/CMakeFiles/etl_tests.dir/murmurhash3.cpp.o -c /home/jaskij/projects/deps/etl/test/murmurhash3.cpp
In file included from /home/jaskij/projects/deps/etl/test/murmurhash3.cpp:10:
/home/jaskij/projects/deps/etl/test/../include/etl/platform.h:361:25: error: identifier ‘char8_t’ is a keyword in C++20 [-Werror=c++20-compat]
  361 |   typedef uint_least8_t char8_t;
```

### PR DESCRIPTION
**Pull request by jaskij**
Fix #906

### CODE REVIEW

**Comment by jaskij** [comment]
Explaining the pragmas:

```cpp
#pragma GCC diagnostic push						// store current diagnostics setup
#pragma GCC diagnostic ignored "-Wc++20-compat"	// disable C++20 compat warning

// code goes here

#pragma GCC diagnostic pop						// resture previously stored diagnostic setup
```

**Comment by jaskij** [comment]
I went with the pragma approach because this is the only place which causes the error

**Comment by jwellbelove** [comment]
For to control warnings so far I've created headers that enable and disable them.
See example `include/etl/private/diagnostic_array_bounds_push.h` and `include/etl/private/diagnostic_pop.h`

**Comment by jaskij** [comment]
Thank you for pointing that out, moved the diagnostics to their own file.

**Pull request merged**
