### PR TITLE
Feature/pool ext  variant pool ext

### PR DESCRIPTION
**Pull request by daniel-brosche**
as discussed in #375

### CODE REVIEW

**Comment by daniel-brosche** [comment]
Everything seems to work but two tests fail which has nothing to do with my changes:
../test/test_delegate.cpp:1021:1: error: Failure in test_call_if_and_not_valid_returning_void: !function_called
../test/test_delegate.cpp:1022:1: error: Failure in test_call_if_and_not_valid_returning_void: !parameter_correct
FAILURE: 1 out of 3951 tests failed (2 failures).
Test time: 4.38 seconds.

**Comment by daniel-brosche** [comment]
@jwellbelove here are the states of function_called and parameter_correct

image

**Comment by jwellbelove** [comment]
`function_called` and `parameter_correct` should have both been set to `false` in `SetupFixture`.
As `was_called` is `false`, that means that no function that would have set them to `true` was called.
I'm not sure how they get the values that you are seeing!

**Comment by jwellbelove** [comment]
image

**Comment by daniel-brosche** [comment]
What is your target system?

**Comment by jwellbelove** [comment]
Although I don't get the unit test fail with CMake using GCC or clang, I do get it if I compile using meson (same version of GCC)

**Comment by jwellbelove** [comment]
OK, I seem to have found the issue.
I moved `SetupFixture` into the anonymous namespace with the unit tests and the test now pass.

**Comment by daniel-brosche** [comment]
strange issue, when I execute just the single test case (without moving SetupFixture) then the test also pass - just mystic

**Comment by daniel-brosche** [comment]
have no double checked and it works also on my side when moving SetupFixture into the namespace

**Comment by daniel-brosche** [comment]
is my source Ok to approval the workflows?

**Pull request merged**
