### PR TITLE
Include new on megaAVR Boards (Arduino Nano Every)

### PR DESCRIPTION
**Pull request by HpLightcorner**
Addressing #312

### CODE REVIEW

**Comment by HpLightcorner** [comment]
Okay, that is interesting, seems like Arduino makes a Workaround necessary here? good that you set up all the tests!

**Comment by HpLightcorner** [comment]
@jwellbelove I tested this branch on some Arduino-Targets. From my perspective this could be a nice solution as management of the '#include <new>' comes into one central file in the private folder. However, it is necessary to check if there is already a builtin version of 'placement new'. Not sure how to do this compiler-independent.

**Comment by HpLightcorner** [comment]
@jwellbelove I think  `ETL_NO_NEW_HEADER_AVAILABLE` might be the most easy to use solution for the given problem - if someone has to use a platform with these specific needs the adjustment in `etl_profile.h` seems to be the most easy way. And ETL does only use placement new operator as far as I have seen, so everything should be fine.

**Comment by HpLightcorner** [comment]
image

**Comment by jwellbelove** [comment]
I've pulled it into a hotfix branch to check over the changes.

**Comment by jwellbelove** [comment]
I've pulled it into a hotfix branch to check over the changes.

**Pull request merged**
